import type { Metadata } from "next";

/**
 * Application metadata for SEO and browser display
 */
export const metadata: Metadata = {
  title: "Jeff Ordway",
  description: "Generated by create next app",
};
