import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainLayout, Header, Footer } from "@/components/layout";

const primaryFont = Inter({
  variable: "--font-main",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jeff Ordway ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} antialiased`}
      >
        <MainLayout showHeader showFooter>
          <Header />
          {children}
          <Footer copyrightText={`© ${new Date().getFullYear()} Jeff Ordway`} />
        </MainLayout>
      </body>
    </html>
  );
}
