import { PageLayout, Section, Container } from "@/components/layout";
import { Heading, Text } from "@/components/ui/typography";

export default function PrivacyPolicy() {
  return (
    <PageLayout 
      showHero={false}
    >
      <Section className="pt-20 md:pt-24 py-10 sm:py-12 md:py-16">
        <Container width="narrow">
          <Heading>Privacy Policy</Heading>
          <Text className="mt-6 mb-8">
            Last updated: March 23, 2025
          </Text>
          
          <div className="mb-8 p-4 bg-gray-100/50 border border-gray-200 rounded-md">
            <Text className="font-medium mb-2">Cookie Consent Notice</Text>
            <Text className="text-sm text-gray-700">This website uses cookies, including those from Google Analytics, to enhance your browsing experience and analyze website traffic. By continuing to use this website, you consent to our use of cookies. You can manage your cookie preferences through your browser settings or opt out of Google Analytics tracking using the Google Analytics opt-out browser add-on.</Text>
          </div>
          
          <div className="space-y-8">
            <div>
              <Heading as="h2" className="mb-4">Introduction</Heading>
              <Text>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </Text>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4">Interpretation and Definitions</Heading>
              <Text className="mb-4">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </Text>
              
              <Heading as="h3" className="mb-3 mt-6">Definitions</Heading>
              <Text className="mb-4">For the purposes of this Privacy Policy:</Text>
              
              <ul className="list-disc pl-6 space-y-3">
                <li>
                  <Text><span className="font-bold">Account</span> means a unique account created for You to access our Service or parts of our Service.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Company</span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Neilson Ossowski Creative LLC, 1317 Edgewater Dr Suite 5758, Orlando FL 32804.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Country</span> refers to: Florida, United States</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Personal Data</span> is any information that relates to an identified or identifiable individual.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Service</span> refers to the Website.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Website</span> refers to Jeff Ordway Portfolio, accessible from <a href="https://jeffordway.com" className="text-primary hover:text-primary-light underline" rel="external nofollow noopener" target="_blank">https://jeffordway.com</a></Text>
                </li>
                <li>
                  <Text><span className="font-bold">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
                </li>
              </ul>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4 mt-8">Collecting and Using Your Personal Data</Heading>
              
              <Heading as="h3" className="mb-3 mt-6">Types of Data Collected</Heading>
              
              <Heading as="h4" className="mb-2 mt-4">Personal Data</Heading>
              <Text className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</Text>
              
              <ul className="list-disc pl-6 space-y-2 mb-6">
                <li><Text>Email address</Text></li>
                <li><Text>First name and last name</Text></li>
                <li><Text>Usage Data</Text></li>
              </ul>
              
              <Heading as="h4" className="mb-2 mt-4">Usage Data</Heading>
              <Text className="mb-4">Usage Data is collected automatically when using the Service.</Text>
              
              <Text className="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</Text>
              
              <Text className="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</Text>
              
              <Text className="mb-4">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</Text>
              
              <Heading as="h4" className="mb-2 mt-4">Tracking Technologies and Cookies</Heading>
              <Text className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</Text>
              
              <ul className="list-disc pl-6 space-y-3 mb-6">
                <li>
                  <Text><span className="font-bold">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</Text>
                </li>
                <li>
                  <Text><span className="font-bold">Google Analytics.</span> We use Google Analytics, a web analytics service provided by Google LLC ("Google"). Google Analytics uses cookies to help us analyze how users use our website. The information generated by the cookie about your use of our website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of our website, compiling reports on website activity for us and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google.</Text>
                </li>
              </ul>
              
              <Text className="mb-4">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</Text>
              
              <Text className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</Text>
              
              <ul className="list-disc pl-6 space-y-6 mb-6">
                <li>
                  <Text className="font-bold">Necessary / Essential Cookies</Text>
                  <Text>Type: Session Cookies</Text>
                  <Text>Administered by: Us</Text>
                  <Text>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</Text>
                </li>
                <li>
                  <Text className="font-bold">Cookies Policy / Notice Acceptance Cookies</Text>
                  <Text>Type: Persistent Cookies</Text>
                  <Text>Administered by: Us</Text>
                  <Text>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</Text>
                </li>
                <li>
                  <Text className="font-bold">Functionality Cookies</Text>
                  <Text>Type: Persistent Cookies</Text>
                  <Text>Administered by: Us</Text>
                  <Text>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</Text>
                </li>
                <li>
                  <Text className="font-bold">Analytics Cookies</Text>
                  <Text>Type: Persistent Cookies</Text>
                  <Text>Administered by: Google</Text>
                  <Text>Purpose: These cookies are used to collect information about how visitors use our website. We use the information to compile reports and to help us improve the website. The cookies collect information in an anonymous form, including the number of visitors to the website, where visitors have come to the website from and the pages they visited. <a href="https://policies.google.com/privacy" className="text-primary hover:text-primary-light underline" rel="external nofollow noopener" target="_blank">Read Google's privacy policy</a>.</Text>
                </li>
              </ul>
              
              <Heading as="h3" className="mb-3 mt-6">Google Analytics</Heading>
              <Text className="mb-4">We use Google Analytics to analyze the use of our website. Google Analytics gathers information about website use by means of cookies. The information gathered relating to our website is used to create reports about the use of our website.</Text>
              
              <Text className="mb-4">We have implemented the following measures to ensure compliance with privacy regulations:</Text>
              
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li><Text>IP anonymization (IP addresses are truncated within the EU before being stored)</Text></li>
                <li><Text>Data retention periods are set to the minimum necessary period</Text></li>
                <li><Text>Data sharing with Google is limited to the necessary minimum</Text></li>
                <li><Text>We have a Data Processing Agreement with Google</Text></li>
              </ul>
              
              <Text className="mb-4">Google's privacy policy is available at: <a href="https://policies.google.com/privacy" className="text-primary hover:text-primary-light underline" rel="external nofollow noopener" target="_blank">https://policies.google.com/privacy</a></Text>
              
              <Text className="mb-4">You can opt out of Google Analytics by installing the Google Analytics opt-out browser add-on which is available at: <a href="https://tools.google.com/dlpage/gaoptout" className="text-primary hover:text-primary-light underline" rel="external nofollow noopener" target="_blank">https://tools.google.com/dlpage/gaoptout</a></Text>
              
              <Heading as="h3" className="mb-3 mt-6">Use of Your Personal Data</Heading>
              <Text className="mb-4">The Company may use Personal Data for the following purposes:</Text>
              
              <ul className="list-disc pl-6 space-y-3 mb-6">
                <li>
                  <Text><span className="font-bold">To provide and maintain our Service</span>, including to monitor the usage of our Service.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">To manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">To manage Your requests:</span> To attend and manage Your requests to Us.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">For business transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</Text>
                </li>
                <li>
                  <Text><span className="font-bold">For other purposes:</span> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</Text>
                </li>
              </ul>
              
              <Text className="mb-4">We may share Your personal information in the following situations:</Text>
              
              <ul className="list-disc pl-6 space-y-3 mb-6">
                <li><Text><span className="font-bold">With Service Providers:</span> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</Text></li>
                <li><Text><span className="font-bold">For business transfers:</span> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</Text></li>
                <li><Text><span className="font-bold">With Affiliates:</span> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</Text></li>
                <li><Text><span className="font-bold">With business partners:</span> We may share Your information with Our business partners to offer You certain products, services or promotions.</Text></li>
                <li><Text><span className="font-bold">With other users:</span> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</Text></li>
                <li><Text><span className="font-bold">With Your consent:</span> We may disclose Your personal information for any other purpose with Your consent.</Text></li>
              </ul>
            
              <Heading as="h3" className="mb-3 mt-6">Retention of Your Personal Data</Heading>
              <Text className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</Text>
              
              <Text className="mb-4">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</Text>
              
              <Heading as="h3" className="mb-3 mt-6">Transfer of Your Personal Data</Heading>
              <Text className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</Text>
              
              <Text className="mb-4">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</Text>
              
              <Text className="mb-4">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</Text>
              
              <Heading as="h3" className="mb-3 mt-6">Your Data Protection Rights</Heading>
              
              <Heading as="h4" className="mb-2 mt-4">GDPR Privacy Rights (For European Economic Area Residents)</Heading>
              <Text className="mb-4">If you are a resident of the European Economic Area (EEA), you have certain data protection rights under the General Data Protection Regulation (GDPR). We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</Text>
              
              <Text className="mb-4">Under the GDPR, you have the following rights:</Text>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li><Text>The right to access – You have the right to request copies of your personal data.</Text></li>
                <li><Text>The right to rectification – You have the right to request that we correct any information you believe is inaccurate or complete information you believe is incomplete.</Text></li>
                <li><Text>The right to erasure – You have the right to request that we erase your personal data, under certain conditions.</Text></li>
                <li><Text>The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.</Text></li>
                <li><Text>The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.</Text></li>
                <li><Text>The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.</Text></li>
              </ul>
              
              <Heading as="h4" className="mb-2 mt-4">CCPA/CPRA Privacy Rights (For California Residents)</Heading>
              <Text className="mb-4">The California Consumer Privacy Act (CCPA) and the California Privacy Rights Act (CPRA) provide California residents with specific rights regarding their personal information. This section describes your CCPA/CPRA rights and explains how to exercise those rights.</Text>
              
              <Text className="mb-4">Under the CCPA/CPRA, you have the following rights:</Text>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li><Text>Right to know – You have the right to request that we disclose certain information to you about our collection and use of your personal information over the past 12 months.</Text></li>
                <li><Text>Right to delete – You have the right to request that we delete any of your personal information that we collected from you and retained, subject to certain exceptions.</Text></li>
                <li><Text>Right to opt-out of sales – You have the right to opt-out of the sale of your personal information. Note that we do not sell your personal information.</Text></li>
                <li><Text>Right to non-discrimination – We will not discriminate against you for exercising any of your CCPA/CPRA rights.</Text></li>
                <li><Text>Right to limit use and disclosure of sensitive personal information – You have the right to limit the use and disclosure of sensitive personal information.</Text></li>
                <li><Text>Right to correct inaccurate personal information – You have the right to request correction of inaccurate personal information.</Text></li>
              </ul>
              
              <Text className="mb-4">To exercise the rights described above, please submit a verifiable consumer request to us by contacting us using the contact information provided in this Privacy Policy.</Text>
              
              <Heading as="h4" className="mb-2 mt-4">General Data Deletion Rights</Heading>
              <Text className="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</Text>
              
              <Text className="mb-4">Our Service may give You the ability to delete certain information about You from within the Service.</Text>
              
              <Text className="mb-4">You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</Text>
              
              <Text className="mb-4">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</Text>
              
              <Heading as="h3" className="mb-3 mt-6">Disclosure of Your Personal Data</Heading>
              
              <Heading as="h4" className="mb-2 mt-4">Business Transactions</Heading>
              <Text className="mb-4">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</Text>
              
              <Heading as="h4" className="mb-2 mt-4">Law enforcement</Heading>
              <Text className="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</Text>
            
              <Heading as="h4" className="mb-2 mt-4">Other legal requirements</Heading>
              <Text className="mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</Text>
              
              <ul className="list-disc pl-6 space-y-2 mb-6">
                <li><Text>Comply with a legal obligation</Text></li>
                <li><Text>Protect and defend the rights or property of the Company</Text></li>
                <li><Text>Prevent or investigate possible wrongdoing in connection with the Service</Text></li>
                <li><Text>Protect the personal safety of Users of the Service or the public</Text></li>
                <li><Text>Protect against legal liability</Text></li>
              </ul>
              
              <Heading as="h3" className="mb-3 mt-6">Security of Your Personal Data</Heading>
              <Text className="mb-4">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</Text>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4 mt-8">Children's Privacy</Heading>
              <Text className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</Text>
              
              <Text className="mb-4">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</Text>
              
              <Text className="mb-4">The Children's Online Privacy Protection Act (COPPA) regulates online collection of information from persons under the age of 13. It is our policy to refrain from knowingly collecting or maintaining personal information relating to any person under the age of 13. If you are under the age of 13, please do not supply any personal information through the website. If you are under the age of 13 and have already provided personal information, please have your parent or guardian contact us immediately using the information provided in the Contact Us section so that we can remove such information from our files.</Text>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4 mt-8">Links to Other Websites</Heading>
              <Text className="mb-4">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</Text>
              
              <Text className="mb-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</Text>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4 mt-8">CalOPPA Compliance</Heading>
              <Text className="mb-4">The California Online Privacy Protection Act (CalOPPA) requires commercial websites and online services to post a privacy policy. According to CalOPPA, we agree to the following:</Text>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li><Text>Users can visit our site anonymously.</Text></li>
                <li><Text>Our Privacy Policy link includes the word 'Privacy' and can easily be found on the home page.</Text></li>
                <li><Text>You will be notified of any Privacy Policy changes on our Privacy Policy Page.</Text></li>
                <li><Text>You can change your personal information by contacting us.</Text></li>
              </ul>
              
              <Text className="mb-4">Our website honors Do Not Track signals and does not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place. DNT is a preference you can set in your web browser to inform websites that you do not want to be tracked.</Text>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4 mt-8">International Transfers of Personal Data</Heading>
              <Text className="mb-4">Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</Text>
              
              <Text className="mb-4">If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</Text>
              
              <Text className="mb-4">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</Text>
              
              <Text className="mb-4">We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</Text>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4 mt-8">Changes to this Privacy Policy</Heading>
              <Text className="mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</Text>
              
              <Text className="mb-4">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</Text>
              
              <Text className="mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</Text>
              
              <Text className="mb-4">If we make material changes to how we treat our users' personal information, we will notify you through a notice on the website home page and/or by email to the primary email address specified in your account.</Text>
            </div>
            
            <div>
              <Heading as="h2" className="mb-4 mt-8">Contact Us</Heading>
              <Text className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</Text>
              
              <ul className="list-disc pl-6 mb-6">
                <li><Text>By visiting this page on our website: <a href="https://jeffordway.com/contact" className="text-primary hover:text-primary-light underline" rel="external nofollow noopener" target="_blank">https://jeffordway.com/contact</a></Text></li>
              </ul>
            </div>
          </div>
        </Container>
      </Section>
    </PageLayout>
  );
}
